### ISSUE TITLE
Link to Microsoft Azure Availability Zones Available points to staging doc

### ISSUE THREAD

**Issue by npintaux** [pivotal-cf/pcf-release-notes#162]
In paragraph https://docs.pivotal.io/pivotalcf/2-5/pcf-release-notes/breaking-changes.html#azure-azs, the last line states:

For more information about Azure AZs, see Microsoft Azure Availability Zones Available (link).

The last link actually points to https://docs-pcf-staging.cfapps.io which requires a login/pwd.

**Comment by mlimonczenko** [comment]
This is resolved! Thank you, @npintaux.
