### ISSUE TITLE
PDF download link returns verison 2.3 vs 2.6

### ISSUE THREAD

**Issue by Houlistonm** [pivotal-cf/pcf-release-notes#174]
Navigate to this link: 
https://docs.pivotal.io/pivotalcf/2-6/pcf-release-notes/index.html
Verify the 2.6 version on the pull down.
click on the PDF link 
I was expecting 2.6, not 2.3.

Opened the downloaded PDF just in case this was a naming issue and not a content issue.,
The 2.3 file has version 2.3 published 24 Sept 2018 on the title page.

**Comment by ljarzynski** [comment]
HI @Houlistonm. Thank you for creating this issue. I'm working on creating the PCF v2.6 PDF right now. I'll update this issue shortly.
