### ISSUE TITLE
 "In-container CF helper assets are transferred into app containers securely" Feature improvement isn't included in v2.7 release notes

### ISSUE THREAD

**Issue by heyjcollins** [pivotal-cf/pcf-release-notes#200]
In reviewing the [current v2.7 release notes](https://docs.pivotal.io/pivotalcf/2-7/pcf-release-notes/runtime-rn.html#2.7.0-build.191) I don't see a call out for the security enhancement described in [Aha! card ERT-560](https://pcf.aha.io/features/ERT-560).

This feature improvement was a x-functional effort between capi and diego teams. The `2.7.0-beta.1` build includes both capi-release v1.84.0 and diego-release v2.34.0 which collectively enable the enhancement.

**Comment by ljarzynski** [comment]
Thanks for filing this, @heyjcollins. @selzoc @mariash Is this something you could help us write a note for to add to the release notes?

**Comment by heyjcollins** [comment]
Hey @ljarzynski - Sorry for the delayed response here. 

Below you'll find content related to this change. Hopefully it will suffice. Diego team is shorthanded this and next week due to CF Summit EU.

- Content from the [**PAS v2.7 kickoff deck**](https://docs.google.com/presentation/d/1bZB-D_jo570-cFW6AoDmMZDZXt_lB1oNN2GX55wfbBE/edit#slide=id.g583c83ac26_49_223)
```
In-container CF helper assets ("app lifecycles") are transferred into app containers securely [aha]
Today the Diego file-server transmits these helper assets over plain HTTP inside the PAS deployment, which requires some customers to make security exceptions for PAS or to use the dreaded IPsec add-on. 
Moving to a secure transport method allows PAS operators to deploy PAS with less organizational friction and with less reliance on security add-ons that often cause additional problems.
```

- Content from the [**Aha! card**](https://pcf.aha.io/features/ERT-560) associated with this change:
```
These helper assets are the "app lifecycle" binaries that do some last-mile, in-container setup for CF app instances, such as setting certain fields in the VCAP_APPLICATION environment variable and populating data in VCAP_SERVICES. Today, the Diego file-server hosts these assets over plain HTTP, and CC specifies their locations as part of the DesiredLRP and Task specifications. This insecure channel potentially leaves them available for a man-in-the-middle attack.

Chosen solution:
Diego file-server transitions to HTTPS (dual, then eventually HTTPS-only); one-way should suffice, none of these assets are sensitive
```

- The OSS CF Diego Tracker Stories associated with this change:
  - https://www.pivotaltracker.com/story/show/166882706
  - https://www.pivotaltracker.com/story/show/165913951

Hopefully this is helpful. Feel free to reach out to [**#cf-deigo**](https://pivotal.slack.com/messages/C3MGYF9B9) in Pivotal Slack if you need more assistance.

Cheers,

Josh

**Comment by mlimonczenko** [comment]
Hello @heyjcollins,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
