### ISSUE TITLE
Opsmgr 2.9.5 release notes not published on tanzu docs (/thanks for having this be in git)

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/pcf-release-notes#320]
This isn't a complaint or anything, I just want to share why I love having these release notes in the open:

Just a heads up, as of writing this issue (6/17/20 at ~12:40pm central), the release notes for opsmgr 2.9.5 are not published on the tanzu/pivotal.io docs site (the current highest it goes is 2.9.4), but the product has been available for download for a few days.

This isn't a huge deal, I imagine things are just moving through update pipelines, but because the docs are OSS I can just look [at the opsmgr 2.9.5 release notes PR listed here](https://github.com/pivotal-cf/pcf-release-notes/commit/8eadd5340d0b30cef8e65bf8bda86c8752dfb2b5). And I can keep an eye on any release-candidate updates every so often just to be more prepared about what changes might be coming down the pike before the official release.

I want to thank you all for the work you all do to keep the doc professional, clean, updated, and able to contribute (whether that's a good thing is highly debatable, I know >_>).

That's all. Just posting this because I think it's an excellent validation of why having the doc be version controlled and open is really valuable. Maybe you all as maintainers hate it 😉 , but I want you to know that as a consumer of these products you all have really helped me out

thanks 👍  we can close this whenever, no worries

screencaps of pivnet/tanzu:

![Screen Shot 2020-06-17 at 12 37 08 PM](https://user-images.githubusercontent.com/5619476/84931297-3477b780-b098-11ea-8c8d-68566c29f7f7.png)
![Screen Shot 2020-06-17 at 12 37 18 PM](https://user-images.githubusercontent.com/5619476/84931293-33df2100-b098-11ea-84b4-97edfcfb21b9.png)

**Comment by paigecalvert** [comment]
Hi @aegershman, thank you so much for reaching out, catching this, and for your kind feedback!

Looks like we had forgot to push the 2.9 pipeline to production. You can see the 2.9.5 release notes live now: https://docs.pivotal.io/platform/2-9/release-notes/opsmanager-rn.html#2-9-5

We love that others can contribute to the docs, too! Not only is it a big help to us, but it also helps make sure that the doc stays as up-to-date as possible. This GitHub issue is a perfect example of that!

Thanks again :)
