### ISSUE TITLE
1.7 Tile author release notes don't mention change from instance_definitions to instance_definition

### ISSUE THREAD

**Issue by william-tran** [pivotal-cf/pcf-release-notes#47]
Is this the only place to look for changes to tile metadata structure when moving to v1.7 metadata?

http://docs.pivotal.io/pivotalcf/1-7/pcf-release-notes/opsmanager-rn.html#tile-authors

It should mention the change from instance_definitions (array) to instance_definition (object)

https://github.com/pivotal-cf/docs-partners/commit/98071fc58ae7b09dc2ac18c9ae81364dbb9af856#diff-53afaab04f3f877756a66316f1e373ebR379

**Comment by william-tran** [comment]
Also please note that  `single_az_only` is now **required**, not just that you can specify this, as the docs mention.

**Comment by pspinrad** [comment]
Thanks @william-tran -- how's this look?
http://docs-pcf-staging.cfapps.io/pivotalcf/1-7/pcf-release-notes/opsmanager-rn.html#tile-authors

**Comment by william-tran** [comment]
I see the mention of single az:
>Tile authors can limit a product’s jobs to a single AZ.

But it still doesn't mention that `single_az_only` is required.

**Comment by pspinrad** [comment]
Thanks @william-tran -- so how does `single_az_only` work?  It's a required field that you set to either `true` or `false`?
