### ISSUE TITLE
Release Notes version drop-down links are broken

### ISSUE THREAD

**Issue by micahyoung** [pivotal-cf/pcf-release-notes#49]
<img width="503" alt="screen shot 2017-04-12 at 4 13 06 pm" src="https://cloud.githubusercontent.com/assets/210312/24977406/f3e79190-1f9a-11e7-8615-05838ab761f6.png">

## Issues:
* Links for 1.10 through 1.6 are broken.
* Appears to be broken due to using http instead of https

**Comment by bentarnoff** [comment]
The links work on our end. Maybe you have a browser extension that prevents you from viewing the unsecured version of a site? In any case, we will change the links to point users to the HTTPS version of the site. Thanks!
