### ISSUE TITLE
Error in release notes (Default SSH Access)

### ISSUE THREAD

**Issue by paulc4** [pivotal-cf/pcf-release-notes#50]
**Disable Default SSH Access for New Applications**

Previously, application SSH access was previously enabled globally as a feature in Cloud Foundry ...

No need to use _previously_ twice

**Comment by ljarzynski** [comment]
Thanks @paulc4 ! Just pushed a commit to address this: https://github.com/pivotal-cf/pcf-release-notes/commit/b285c0f91693b40db33a7278ca2cda064cebc425

Should be on the site shortly.
