### ISSUE TITLE
1.10.25 Release note web link results in 404

### ISSUE THREAD

**Issue by steads** [pivotal-cf/pcf-release-notes#58]
This section of the 1.10.25 Release Note produces a 404 Not Found Error
* Bumps cf-autoscaling-release to v84.5 [Release
Notes](https://github.com/pivotal-cf/cf-autoscaling-release/releases/tag/v84.5).

**Comment by animatedmax** [comment]
Thank you for pointing this out, @steads 
Since the linked page isn't publicly viewable, and we haven't linked to other cf-autoscaling-release Release Notes before, we have removed the link.

https://docs.pivotal.io/pivotalcf/1-10/pcf-release-notes/runtime-rn.html#1.10.25
