### ISSUE TITLE
3445 is up to version .16 and this page stops at .7

### ISSUE THREAD

**Issue by labrown** [pivotal-cf/pcf-release-notes#61]
https://docs.pivotal.io/pivotalcf/1-12/pcf-release-notes/stemcell-rn.html

Where are the release notes for version .8 through .16?

**Comment by bentarnoff** [comment]
Hey @labrown thanks for bringing this to our attention. We've updated this topic to include `3445.7`, `3445.11`, and `3445.16`, which are the stemcells provided on Pivnet for use with PCF 1.12. I'm closing this issue but please feel free to reach out if you have more questions or concerns.
