### ISSUE TITLE
Escaping of * not working for 1.12.9 table

### ISSUE THREAD

**Issue by skibum55** [pivotal-cf/pcf-release-notes#66]
Escaping of * not working for 1.12.9 table
https://github.com/pivotal-cf/pcf-release-notes/blob/1.12/runtime-rn.html.md.erb#L63
<img width="571" alt="screen shot 2017-12-20 at 12 37 00 pm" src="https://user-images.githubusercontent.com/3813241/34225221-df148436-e582-11e7-8a15-bf775f96e65d.png">
It is working for lower versions (e.g. https://github.com/pivotal-cf/pcf-release-notes/blob/1.12/runtime-rn.html.md.erb#L313)
<img width="560" alt="screen shot 2017-12-20 at 12 39 16 pm" src="https://user-images.githubusercontent.com/3813241/34225220-df024776-e582-11e7-845f-00f10c283c5c.png">

**Comment by skibum55** [comment]
Also, it would be nice to have the cc API version in the table.  See https://github.com/cloudfoundry/capi-release/releases/tag/1.40.0
<img width="344" alt="screen shot 2017-12-20 at 12 43 18 pm" src="https://user-images.githubusercontent.com/3813241/34225356-692979c4-e583-11e7-9656-e9da3752dc01.png">

**Comment by seviet** [comment]
@skibum55 we fixed the table formatting but we'll need to ask RelEng @kenchenpcf @ryanmoran to update the table with CC API version
