### ISSUE TITLE
Stemcell in version table for ERT 1.12.13 does not exist

### ISSUE THREAD

**Issue by jpluscplusm** [pivotal-cf/pcf-release-notes#75]
I've raised PR https://github.com/pivotal-cf/pcf-release-notes/pull/74 to fix this based on the externally-visible information I have access to.

**Comment by animatedmax** [comment]
Thank you @jpluscplusm 
Stemcell version should now be correct.
https://docs.pivotal.io/pivotalcf/1-12/pcf-release-notes/runtime-rn.html
