### ISSUE TITLE
Remove 2012R2 reference in PASW release notes

### ISSUE THREAD

**Issue by awmartin** [pivotal-cf/pcf-release-notes#86]
PASW 2012R2 is an offering that's approaching EOL. Let's not draw visibility to it and just remove the note.

https://github.com/pivotal-cf/pcf-release-notes/blob/2.1/windows-rn.html.md.erb
https://github.com/pivotal-cf/pcf-release-notes/blob/2.2/windows-rn.html.md.erb

**Comment by bentarnoff** [comment]
Thanks @genevieve. Looks like the corresponding story in the Docs backlog was completed and accepted but we didn't close this issue out. Closing now.
